package ringbuffer_test

import (
	"fmt"

	"github.com/sevagh/ringworm/ringbuffer1"
)

func ExampleRingbuffer() {
	coolText := []byte("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt nisi tincidunt velit euismod gravida. Aenean at turpis nec lectus faucibus lobortis vitae at arcu. In hac habitasse platea dictumst. Praesent commodo tellus vitae massa maximus porta. Etiam tortor justo, pulvinar nec tempus sit amet, sodales sit amet libero. Nullam non massa mi. Aenean laoreet arcu nec efficitur interdum. Donec vel neque id enim ullamcorper congue nec cursus metus. In hac habitasse platea dictumst. Vestibulum gravida enim non luctus consectetur. Maecenas sit amet risus id orci ultrices viverra dapibus a justo. Nulla facilisi. Nulla velit justo, convallis vel rhoncus a, laoreet ac lectus. Duis ex augue, facilisis id tortor eu, vulputate consectetur felis. Curabitur vitae aliquam nisi. Fusce blandit placerat metus eu elementum. Nam sed lectus tellus. Etiam nec eros sed turpis pulvinar interdum in sed quam. Phasellus tempus lobortis justo. Nullam vulputate nisl sed felis porta, sit amet auctor lectus porttitor. Aenean neque quam, luctus viverra felis eu, feugiat venenatis diam. Nulla facilisi. Nullam luctus augue erat, sit amet suscipit tortor eleifend non. Maecenas congue luctus nisi, ac ullamcorper ligula tristique nec. Nullam non magna bibendum, pretium lorem eget, faucibus nisl. Praesent risus tellus, commodo vitae convallis ac, dictum at felis. Cras lacus risus, accumsan nec lectus sit amet, consectetur pharetra ante. Nulla eget bibendum erat, ut placerat sapien. Mauris nulla magna, fringilla sed turpis eget, sodales luctus orci. Vestibulum lectus sapien, facilisis nec eros vitae, dictum feugiat purus. Phasellus felis nunc, condimentum et dolor mattis, sagittis varius mauris. Proin diam turpis, efficitur vitae ipsum convallis, cursus imperdiet libero. Etiam porta sapien sapien, quis fringilla magna porttitor a. Maecenas ac urna vitae ante dapibus convallis. Pellentesque sit amet varius justo. Morbi tristique elementum pellentesque. Vivamus id sodales risus, eget condimentum libero. Sed maximus, metus vitae mollis ultricies, ligula purus sodales enim, ut accumsan felis nibh non enim. Phasellus in orci sem. Sed ac felis rutrum, aliquet felis eget, tristique sem. Quisque non justo pharetra, condimentum nibh sit amet, condimentum neque. Donec a odio at quam hendrerit eleifend at ac mi. Vivamus a iaculis sem, quis tempor ante. Vestibulum quis ligula nisi. Vestibulum commodo orci at lectus consequat, consectetur eleifend est tristique. Proin consectetur elementum metus eget fermentum. Sed facilisis sapien id orci cursus pellentesque.")

	ringbuf := ringbuffer.NewRingbuffer(16)
	oneByte := make([]byte, 1)

	for _, b := range coolText {
		oneByte[0] = b
		ringbuf.Write(oneByte)
		fmt.Printf("%s", string(ringbuf.Drain()))
	}

	// Output: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt nisi tincidunt velit euismod gravida. Aenean at turpis nec lectus faucibus lobortis vitae at arcu. In hac habitasse platea dictumst. Praesent commodo tellus vitae massa maximus porta. Etiam tortor justo, pulvinar nec tempus sit amet, sodales sit amet libero. Nullam non massa mi. Aenean laoreet arcu nec efficitur interdum. Donec vel neque id enim ullamcorper congue nec cursus metus. In hac habitasse platea dictumst. Vestibulum gravida enim non luctus consectetur. Maecenas sit amet risus id orci ultrices viverra dapibus a justo. Nulla facilisi. Nulla velit justo, convallis vel rhoncus a, laoreet ac lectus. Duis ex augue, facilisis id tortor eu, vulputate consectetur felis. Curabitur vitae aliquam nisi. Fusce blandit placerat metus eu elementum. Nam sed lectus tellus. Etiam nec eros sed turpis pulvinar interdum in sed quam. Phasellus tempus lobortis justo. Nullam vulputate nisl sed felis porta, sit amet auctor lectus porttitor. Aenean neque quam, luctus viverra felis eu, feugiat venenatis diam. Nulla facilisi. Nullam luctus augue erat, sit amet suscipit tortor eleifend non. Maecenas congue luctus nisi, ac ullamcorper ligula tristique nec. Nullam non magna bibendum, pretium lorem eget, faucibus nisl. Praesent risus tellus, commodo vitae convallis ac, dictum at felis. Cras lacus risus, accumsan nec lectus sit amet, consectetur pharetra ante. Nulla eget bibendum erat, ut placerat sapien. Mauris nulla magna, fringilla sed turpis eget, sodales luctus orci. Vestibulum lectus sapien, facilisis nec eros vitae, dictum feugiat purus. Phasellus felis nunc, condimentum et dolor mattis, sagittis varius mauris. Proin diam turpis, efficitur vitae ipsum convallis, cursus imperdiet libero. Etiam porta sapien sapien, quis fringilla magna porttitor a. Maecenas ac urna vitae ante dapibus convallis. Pellentesque sit amet varius justo. Morbi tristique elementum pellentesque. Vivamus id sodales risus, eget condimentum libero. Sed maximus, metus vitae mollis ultricies, ligula purus sodales enim, ut accumsan felis nibh non enim. Phasellus in orci sem. Sed ac felis rutrum, aliquet felis eget, tristique sem. Quisque non justo pharetra, condimentum nibh sit amet, condimentum neque. Donec a odio at quam hendrerit eleifend at ac mi. Vivamus a iaculis sem, quis tempor ante. Vestibulum quis ligula nisi. Vestibulum commodo orci at lectus consequat, consectetur eleifend est tristique. Proin consectetur elementum metus eget fermentum. Sed facilisis sapien id orci cursus pellentesque.
}
